import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Tracker from "@/components/Tracker";
import { getLocale } from "@/lib/i18n";
import { SITE_URL } from "@/lib/seo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// SITE_URL is centralized in lib/seo.ts (env-driven). Swap to a custom domain
// by setting NEXT_PUBLIC_SITE_URL — every canonical, OG and sitemap URL follows.
const SITE_NAME = "Inlet";
const TAGLINE = "One form backend for all your websites";
const DESCRIPTION =
  "The self-hosted form backend that centralizes submissions from all your sites into one dashboard — no SMTP, no per-site setup. White-labeled auto-reply emails, AI + proof-of-work spam blocking, CSV exports. A privacy-first alternative to Formspree, Jotform and Basin.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${TAGLINE}`,
    template: `%s · ${SITE_NAME}`,
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "form backend",
    "form backend service",
    "form API",
    "form system",
    "form management system",
    "form MCP server",
    "MCP form backend",
    "AI form backend",
    "form API for AI agents",
    "form microservice",
    "Formspree alternative",
    "Jotform alternative",
    "Basin alternative",
    "Getform alternative",
    "Web3Forms alternative",
    "self-hosted forms",
    "self-hosted form backend",
    "contact form backend",
    "form without backend",
    "form without SMTP",
    "centralized form submissions",
    "multi-tenant forms",
    "white-label form emails",
    "static site form handler",
    "Astro form backend",
    "Next.js form backend",
    "HTML form to email",
    "form spam protection",
    "proof of work anti-spam",
  ],
  authors: [{ name: SITE_NAME }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  category: "technology",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${TAGLINE}`,
    description: DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
    // og image is generated by app/opengraph-image.tsx (always in sync)
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${TAGLINE}`,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  manifest: "/manifest.json",
  icons: {
    icon: "/icon.svg",
  },
  // Fill these once you verify the property (Google Search Console + Bing
  // Webmaster — Bing indexing is required for ChatGPT citations).
  verification: {
    // google: "your-google-site-verification",
    other: {
      // "msvalidate.01": "your-bing-verification",
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Arm scroll-reveal before paint so hidden→shown transitions run for JS
            clients, while crawlers/no-JS (which never add this class) see all
            content fully visible. */}
        <script
          dangerouslySetInnerHTML={{
            __html: "document.documentElement.classList.add('reveal-ready')",
          }}
        />
        {children}
        <Tracker />
      </body>
    </html>
  );
}
